version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80' # Nginx will listen on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - basenet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
        - basenet

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
        - basenet
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j_test123
      - PORT=3000
    ports:
      - '3000:3000' # Expose the backend on port 3000 of the host
    depends_on:
      - neo4j

  neo4j:
    image: neo4j
    hostname: neo4j
    container_name: neo4j
    networks:
        - basenet
    environment:
      - NEO4J_AUTH=neo4j/neo4j_test123
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - ../neo4j/data:/data
      - ../neo4j/logs:/logs
      - ../neo4j/import:/var/lib/neo4j/import
      - ../neo4j/plugins:/plugins
    ports:
      - '7474:7474' # Neo4j web interface
      - '7687:7687' # Neo4j bolt port

networks:
    basenet:
        name: mynetwork